Statistics refactor
eclipsesource/theia-cloud-lab pull request #38
Opened 2023-01-23 19:52 UTC by ilaydacansinkoc

Current developments include such changes:

- Separation of CPU and Memory Charts.
- Average Memory and CPU Consumption in time.
- CPU and Memory consumption per user

Following Developments:

- List 3 Users that has most Memory and CPU consumption.

2023-01-23 19:57 UTC, DSanyal19 approved these changes, later dismissed

2023-01-23 20:35 UTC, larnon requested changes

2023-01-23 20:35 UTC, larnon commented on src/pages/api/admin/statistics/getTableData.ts
> +      }
No need for this part.

2023-01-23 20:35 UTC, larnon commented on src/pages/api/admin/statistics/getTableData.ts
> +      const workspaceListFromK8s = await k8s.getWorkspaceList();
This is the single source of truth for workspaces and it already comes with user information for each workspace.

2023-01-23 20:35 UTC, larnon commented on src/pages/api/admin/statistics/index.ts
> +}
No need for this API. We already had an API in getTableData.ts for getting all the global tables data in one fetch.

2023-01-23 20:35 UTC, larnon commented on src/pages/admin/statistics.tsx
> +import annotationPlugin from 'chartjs-plugin-annotation';
This import is not used here.

2023-01-23 20:35 UTC, larnon commented on src/components/Graphs/PerUserResourceUsageGraph.tsx
> +const GlobalResourceUsageGraph = () => {
Duplicate component name.

2023-01-23 20:35 UTC, larnon commented on src/components/Graphs/PerUserResourceUsageGraph.tsx
> +export default memo(GlobalResourceUsageGraph);
Duplicate component name.

2023-01-23 20:36 UTC, larnon commented on src/pages/api/admin/statistics/getTableData.ts
> +      const workspaceListFromK8s = await k8s.getWorkspaceList();
This is the single source of truth for workspaces and it already comes with user information for each workspace.

2023-01-23 20:38 UTC, larnon requested changes

2023-01-23 20:38 UTC, larnon commented on src/pages/api/admin/statistics/getTableData.ts
> +      const workspaceListFromK8s = await k8s.getWorkspaceList();
K8s API is the single source of truth for workspaces and it already comes with user information for each workspace.

2023-01-24 22:35 UTC, larnon approved these changes, later dismissed

2023-01-24 23:33 UTC, larnon approved these changes

2023-01-25 18:36 UTC, sevvalekici approved these changes

2023-01-25 18:37 UTC, merged